apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bdt3y6bdy-dotnet-basic
  janus-idp.io/tekton: bdt3y6bdy-dotnet-basic
  backstage.io/kubernetes-id: bdt3y6bdy-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bdt3y6bdy-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
